"""Binding, blinded-packet transformation and deterministic count/gate engine.

Supplied judgments are agent_llm observations, never generated by this module.
Semantic evaluator authority requires separate live calibration and custody.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
PAIRS = {
    ("accepted", "on_target_adequate"),
    ("rejected", "wrong_subject"),
    ("rejected", "wrong_target"),
    ("rejected", "insufficient_context"),
    ("needs-review", "uncertain"),
}


class BoundaryError(ValueError):
    """Input, custody or apparatus precondition failed; no scientific result."""


def require(condition: bool, message: str) -> None:
    if not condition:
        raise BoundaryError(message)


def canonical(value: Any) -> bytes:
    return json.dumps(
        value, sort_keys=True, separators=(",", ":"), ensure_ascii=False, allow_nan=False
    ).encode("utf-8")


def digest(data: bytes) -> str:
    return "sha256:" + hashlib.sha256(data).hexdigest()


def exact(value: Any, keys: set[str], label: str) -> None:
    require(isinstance(value, dict) and set(value) == keys, f"{label}: exact fields required")


def load(path: Path) -> Any:
    def object_hook(items: list[tuple[str, Any]]) -> dict[str, Any]:
        require(len(items) == len(dict(items)), "duplicate JSON keys")
        return dict(items)

    def constant(token: str) -> Any:
        raise BoundaryError(f"nonfinite JSON: {token}")

    try:
        return json.loads(path.read_bytes(), object_pairs_hook=object_hook, parse_constant=constant)
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise BoundaryError(f"unavailable/invalid input: {path.name}") from exc


def write_new(path: Path, value: Any) -> str:
    data = canonical(value)
    with path.open("xb") as stream:
        stream.write(data)
    path.chmod(0o400)
    return digest(data)


def fresh_directory(path: Path) -> None:
    require(not path.exists() and not path.is_symlink(), "output directory must be nonexistent")
    path.mkdir(mode=0o700, parents=False)


def policy() -> dict[str, Any]:
    return load(HERE / "SPEC.json")


def claim_index(claims: dict[str, Any]) -> dict[str, dict[str, Any]]:
    exact(claims, {"schema", "packets"}, "claims")
    require(claims["schema"] == "eb-child-subject-claims-v1", "wrong claims schema")
    spec = policy()["population"]
    require(len(claims["packets"]) == spec["packets"], "expected three real packets")
    index: dict[str, dict[str, Any]] = {}
    parents: set[str] = set()
    packets: set[str] = set()
    for packet in claims["packets"]:
        exact(packet, {"packet_id", "provenance", "parents"}, "claim packet")
        require(
            isinstance(packet["provenance"], str) and bool(packet["provenance"].strip()),
            "declaration provenance missing",
        )
        require(packet["packet_id"] not in packets, "duplicate packet")
        packets.add(packet["packet_id"])
        require(len(packet["parents"]) == spec["parents_per_packet"], "four parents per packet")
        for parent in packet["parents"]:
            exact(parent, {"parent_id", "text", "children"}, "parent")
            require(parent["parent_id"] not in parents, "duplicate parent")
            require(
                isinstance(parent["text"], str) and bool(parent["text"].strip()), "blank parent"
            )
            parents.add(parent["parent_id"])
            require(len(parent["children"]) == 2, "two all_of children required")
            require(len({x["text"] for x in parent["children"]}) == 2, "duplicate obligation")
            for seq, child in enumerate(parent["children"], 1):
                exact(child, {"child_id", "text", "sequence"}, "child")
                require(
                    type(child["sequence"]) is int and child["sequence"] == seq,
                    "noncontiguous child sequence",
                )
                require(child["child_id"] not in index, "duplicate child")
                require(
                    isinstance(child["text"], str) and bool(child["text"].strip()), "blank child"
                )
                index[child["child_id"]] = {
                    **child,
                    "parent_id": parent["parent_id"],
                    "parent_text": parent["text"],
                    "packet_id": packet["packet_id"],
                }
    require(not parents.intersection(index), "parent/child identity collision")
    exclusions = load(HERE / "PREDECESSOR-EVIDENCE.json")["known_failure_exclusions"]
    require(
        not {digest(x["text"].encode()) for x in index.values()}.intersection(
            exclusions["child_text_sha256"]
        ),
        "known RC0 child is ineligible",
    )
    return index


def check_subjects(claims: dict[str, Any], subjects: dict[str, Any]) -> dict[str, Any]:
    ci = claim_index(claims)
    exact(subjects, {"schema", "declarations"}, "subjects")
    require(subjects["schema"] == "eb-child-subject-declarations-v1", "wrong subject schema")
    entries: dict[str, Any] = {}
    inherited: set[str] = set()
    for row in subjects["declarations"]:
        exact(
            row,
            {
                "child_id",
                "anchor",
                "origin",
                "span_start",
                "span_end",
                "origin_text_sha256",
                "wrong_child_id",
                "entity_class",
            },
            "subject declaration",
        )
        cid = row["child_id"]
        require(cid in ci and cid not in entries, "subject mapping/duplicate")
        require(row["origin"] in {"child", "parent"}, "evidence-derived subject forbidden")
        require(isinstance(row["anchor"], str) and bool(row["anchor"].strip()), "blank subject")
        require(
            isinstance(row["entity_class"], str) and bool(row["entity_class"].strip()),
            "entity class needed for credible control",
        )
        origin = ci[cid]["text"] if row["origin"] == "child" else ci[cid]["parent_text"]
        require(row["origin_text_sha256"] == digest(origin.encode()), "subject origin digest")
        start, end = row["span_start"], row["span_end"]
        origin_bytes = origin.encode("utf-8")
        require(
            type(start) is int and type(end) is int and 0 <= start < end <= len(origin_bytes),
            "subject span invalid",
        )
        require(
            origin_bytes[start:end] == row["anchor"].encode("utf-8"),
            "subject must be exact claim-native UTF-8 byte span",
        )
        if row["origin"] == "parent":
            require(
                row["anchor"].casefold() not in ci[cid]["text"].casefold(),
                "inheritance requires elliptical child",
            )
            inherited.add(ci[cid]["packet_id"])
        entries[cid] = row
    require(set(entries) == set(ci), "subject declarations must bind every child")
    require(len(inherited) == 3, "one inherited subject in every packet required")
    for cid, row in entries.items():
        donor = entries.get(row["wrong_child_id"])
        require(
            donor is not None and donor["anchor"].casefold() != row["anchor"].casefold(),
            "wrong-subject control must be a distinct declared anchor",
        )
        require(
            ci[donor["child_id"]]["packet_id"] == ci[cid]["packet_id"]
            and donor["entity_class"] == row["entity_class"],
            "unmatched wrong-subject control",
        )
    return entries


def check_corpus(claims: dict[str, Any], corpus: dict[str, Any]) -> None:
    ci = claim_index(claims)
    exact(corpus, {"schema", "packets"}, "corpus")
    require(corpus["schema"] == "eb-child-subject-corpus-v1", "wrong corpus schema")
    require(len(corpus["packets"]) == 3, "corpus packet count")
    seen: set[str] = set()
    seen_hashes: set[str] = set()
    excluded = set(
        load(HERE / "PREDECESSOR-EVIDENCE.json")["known_failure_exclusions"][
            "source_content_sha256"
        ]
    )
    for packet in corpus["packets"]:
        exact(packet, {"packet_id", "sources"}, "corpus packet")
        require(
            packet["packet_id"] not in seen and bool(packet["sources"]), "duplicate/empty corpus"
        )
        seen.add(packet["packet_id"])
        ids: set[str] = set()
        for source in packet["sources"]:
            exact(source, {"source_id", "media_type", "content", "content_sha256"}, "source")
            require(
                source["media_type"]
                in {"text/plain; charset=utf-8", "text/markdown; charset=utf-8"},
                "unsupported source format",
            )
            require(
                isinstance(source["content"], str) and bool(source["content"].strip()),
                "blank source",
            )
            require(
                digest(source["content"].encode()) == source["content_sha256"],
                "source digest mismatch",
            )
            require(source["source_id"] not in ids, "duplicate source identity")
            require(
                source["content_sha256"] not in seen_hashes | excluded,
                "known specimen or source overlap between real packets",
            )
            ids.add(source["source_id"])
            seen_hashes.add(source["content_sha256"])
    require(seen == {x["packet_id"] for x in ci.values()}, "claim/corpus packet mapping")


def build_packet(result: dict[str, Any], salt: str) -> tuple[dict[str, Any], dict[str, Any]]:
    """Data transformer only: union-pool blinding, without reviewer execution."""
    validate_result(result)
    rows, mapping = [], {}
    for cid, pool in result["pools"].items():
        target = result["targets"][cid]
        for item in pool:
            pid = item["passage_id"]
            alias = hashlib.sha256(canonical([salt, cid, pid])).hexdigest()
            require(alias not in mapping, "alias collision")
            mapping[alias] = [cid, pid]
            rows.append(
                {
                    "alias": alias,
                    "proposition": target["text"],
                    "parent_context": target["parent_text"],
                    "passage": item["text"],
                }
            )
    rows.sort(key=lambda row: row["alias"])
    packet = {
        "schema": "eb-child-subject-review-packet-v1",
        "rubric": load(HERE / "RUBRIC.json"),
        "rows": rows,
    }
    bindings = {
        "schema": "eb-child-subject-mapping-v1",
        "mapping": mapping,
        "result_payload_sha256": digest(canonical(result)),
        "packet_raw_sha256": digest(canonical(packet)),
    }
    return packet, bindings


def validate_result(result: dict[str, Any]) -> None:
    exact(result, {"schema", "binding", "targets", "pools", "selections"}, "retrieval result")
    require(result["schema"] == "eb-child-subject-retrieval-v1", "wrong retrieval schema")
    targets = result["targets"]
    require(len(targets) == 24, "retrieval must bind all 24 children")
    require(set(result["pools"]) == set(targets), "nomination/target binding")
    parents: dict[str, set[str]] = {}
    packets: dict[str, set[str]] = {}
    for cid, target in targets.items():
        exact(target, {"text", "parent_text", "parent_id", "packet_id"}, "target")
        parents.setdefault(target["parent_id"], set()).add(cid)
        packets.setdefault(target["packet_id"], set()).add(target["parent_id"])
    require(len(parents) == 12 and all(len(x) == 2 for x in parents.values()), "all_of mapping")
    require(len(packets) == 3 and all(len(x) == 4 for x in packets.values()), "packet denominator")
    pools = {}
    for cid, rows in result["pools"].items():
        ids = []
        for row in rows:
            exact(row, {"passage_id", "text"}, "reviewable passage")
            ids.append(row["passage_id"])
            require(isinstance(row["text"], str) and bool(row["text"].strip()), "empty passage")
        require(len(ids) == len(set(ids)) and len(ids) <= 30, "union pool duplication/depth")
        pools[cid] = set(ids)
    require(set(result["selections"]) == set(policy()["arms"]), "missing/unregistered arm")
    for arm, selection in result["selections"].items():
        require(set(selection) == set(targets), f"{arm}: incomplete child lanes")
        for cid, ids in selection.items():
            require(
                isinstance(ids, list) and len(ids) <= 3 and len(ids) == len(set(ids)),
                f"{arm}: K overflow/duplicate retention",
            )
            require(set(ids) <= pools[cid], f"{arm}: out-of-pool selection")


def judgments(review: dict[str, Any], packet: dict[str, Any]) -> dict[str, tuple[str, str]]:
    exact(packet, {"schema", "rubric", "rows"}, "review packet")
    require(
        packet["schema"] == "eb-child-subject-review-packet-v1"
        and packet["rubric"] == load(HERE / "RUBRIC.json"),
        "review rubric/schema drift",
    )
    aliases = []
    for row in packet["rows"]:
        exact(row, {"alias", "proposition", "parent_context", "passage"}, "blinded packet row")
        aliases.append(row["alias"])
    require(len(aliases) == len(set(aliases)), "duplicate packet alias")
    exact(review, {"reviewer_id", "session_id", "model_id", "packet_raw_sha256", "rows"}, "review")
    for name in ("reviewer_id", "session_id", "model_id"):
        require(isinstance(review[name], str) and bool(review[name].strip()), f"missing {name}")
    require(review["packet_raw_sha256"] == digest(canonical(packet)), "review packet binding")
    out = {}
    for row in review["rows"]:
        exact(row, {"alias", "decision", "reason"}, "review row")
        require(row["alias"] not in out, "duplicate review alias")
        pair = (row["decision"], row["reason"])
        require(pair in PAIRS, "invalid decision/reason pair")
        out[row["alias"]] = pair
    require(set(out) == {x["alias"] for x in packet["rows"]}, "review alias coverage")
    return out


def calibrate(packet: dict[str, Any], gold: dict[str, Any], reviews: list[dict[str, Any]]) -> bool:
    require(len(reviews) == 2 and len(packet["rows"]) == 8, "two reviewers / eight controls")
    require(
        reviews[0]["reviewer_id"] != reviews[1]["reviewer_id"]
        and reviews[0]["session_id"] != reviews[1]["session_id"],
        "calibration sessions not separate",
    )
    require(reviews[0]["model_id"] == reviews[1]["model_id"], "calibration profile/model mismatch")
    expected = {x["alias"]: (x["decision"], x["reason"]) for x in gold["rows"]}
    require(len(expected) == 8, "control gold coverage")
    # Conjunction is a separate mechanical control: one adequate child is not a parent.
    pair = gold["partial_all_of_aliases"]
    require(
        len(pair) == 2 and sum(expected[x][0] == "accepted" for x in pair) == 1,
        "partial-parent control must discriminate one-child coverage",
    )
    return all(judgments(r, packet) == expected for r in reviews)


def metrics(
    result: dict[str, Any], values: dict[tuple[str, str], tuple[str, str]]
) -> dict[str, Any]:
    output = {}
    targets = result["targets"]
    denominators = {
        cid: sum(values[(cid, p["passage_id"])][0] == "accepted" for p in result["pools"][cid])
        for cid in targets
    }
    for arm, lanes in result["selections"].items():
        covered, parents, per_packet, reasons = set(), {}, {}, {}
        adequate = unsafe = nonuseful = slots = 0
        unique = set()
        per_child = {}
        for cid, ids in lanes.items():
            accepted = sum(values[(cid, pid)][0] == "accepted" for pid in ids)
            if accepted:
                covered.add(cid)
            target = targets[cid]
            parents.setdefault(target["parent_id"], set()).add(cid)
            per_packet.setdefault(target["packet_id"], set()).add(cid)
            adequate += accepted
            slots += len(ids)
            for pid in ids:
                pair = values[(cid, pid)]
                unsafe += pair[1] == "wrong_subject"
                nonuseful += pair[0] != "accepted"
                reasons[pair[1]] = reasons.get(pair[1], 0) + 1
                unique.add(pid)
            denominator = denominators[cid]
            per_child[cid] = {
                "accepted_retained": accepted,
                "accepted_reachable": denominator,
                "recall": accepted / denominator if denominator else None,
                "covered": bool(accepted),
            }
        denominator = sum(denominators.values())
        output[arm] = {
            "required_children": len(covered),
            "complete_parents": sum(children <= covered for children in parents.values()),
            "wrong_subject": unsafe,
            "non_useful": nonuseful,
            "accepted_retained": adequate,
            "accepted_reachable": denominator,
            "recall": adequate / denominator if denominator else None,
            "selected_slots": slots,
            "unique_passages": len(unique),
            "reasons": reasons,
            "per_child": per_child,
            "per_packet": {key: len(cids & covered) for key, cids in per_packet.items()},
            "per_parent": {
                key: {"children_covered": len(cids & covered), "complete": cids <= covered}
                for key, cids in parents.items()
            },
        }
    return output


def decide(m: dict[str, Any]) -> dict[str, Any]:
    t = policy()["thresholds"]

    def dominates(arm: str, controls: list[str]) -> bool:
        x = m[arm]
        return (
            all(
                x["required_children"] - m[ref]["required_children"] >= t["required_child_gain"]
                and x["complete_parents"] - m[ref]["complete_parents"] >= t["complete_parent_gain"]
                and x["wrong_subject"] <= m[ref]["wrong_subject"]
                and x["non_useful"] <= m[ref]["non_useful"]
                for ref in ["A0", "S0"]
            )
            and sum(
                all(x["per_packet"][p] > m[ref]["per_packet"][p] for ref in ["A0", "S0"])
                for p in x["per_packet"]
            )
            >= t["positive_packets"]
            and all(
                x["required_children"] - m[c]["required_children"] >= t["control_margin"]
                for c in controls
            )
        )

    def increment(ref: str) -> bool:
        return m["A3"]["required_children"] - m[ref]["required_children"] >= t[
            "increment_child_gain"
        ] and (
            m["A3"]["wrong_subject"] <= m[ref]["wrong_subject"]
            and m["A3"]["non_useful"] <= m[ref]["non_useful"]
        )

    primary = dominates("A3", ["WS3", "WC3", "L0"])
    child = increment("A2")
    subject = (
        increment("A1")
        and m["A3"]["required_children"] - m["WS3"]["required_children"] >= t["control_margin"]
    )
    labels = []
    if not child:
        labels.append("CHILD_COVERAGE_INCREMENT_NOT_REPRODUCED")
    if not subject:
        labels.append("SUBJECT_IDENTITY_INCREMENT_NOT_REPRODUCED")
    if dominates("A2", ["WS2", "L0"]):
        labels.append("SUPPORTED_SUBJECT_ONLY")
    if dominates("A1", ["WC1", "L0"]):
        labels.append("SUPPORTED_CHILD_ONLY")
    if primary and child and subject:
        labels.append("SUPPORTED_CHILD_AND_SUBJECT")
    if m["A3"]["accepted_reachable"] == 0:
        labels.append("NO_LOCAL_ADEQUACY_OBSERVED_WITHIN_FROZEN_DEPTH")
    return {
        "primary_threshold_pass": primary,
        "child_increment_pass": child,
        "subject_increment_pass": subject,
        "mechanism_results": labels,
        "primary_disposition": "FALSIFIED"
        if not primary
        else "SUPPORTED"
        if child and subject
        else "INCONCLUSIVE",
    }


def tally(
    result: dict[str, Any],
    packet: dict[str, Any],
    mapping: dict[str, Any],
    reviews: list[dict[str, Any]],
    calibration_passed: bool,
) -> dict[str, Any]:
    validate_result(result)
    exact(mapping, {"schema", "mapping", "result_payload_sha256", "packet_raw_sha256"}, "mapping")
    require(
        mapping["result_payload_sha256"] == digest(canonical(result))
        and mapping["packet_raw_sha256"] == digest(canonical(packet)),
        "mapping content binding",
    )
    require(len(reviews) == 2, "exactly two reviewer artifacts")
    require(
        reviews[0]["reviewer_id"] != reviews[1]["reviewer_id"]
        and reviews[0]["session_id"] != reviews[1]["session_id"],
        "reviewers/sessions must differ",
    )
    require(reviews[0]["model_id"] == reviews[1]["model_id"], "decisive reviewer model mismatch")
    a, b = (judgments(r, packet) for r in reviews)
    require(set(mapping["mapping"]) == set(a), "mapping alias set")
    expected = {(cid, row["passage_id"]) for cid, rows in result["pools"].items() for row in rows}
    actual = [tuple(pair) for pair in mapping["mapping"].values()]
    require(
        len(actual) == len(set(actual)) and set(actual) == expected, "mapping/pool pair binding"
    )
    for row in packet["rows"]:
        cid, pid = mapping["mapping"][row["alias"]]
        require(
            row
            == {
                "alias": row["alias"],
                "proposition": result["targets"][cid]["text"],
                "parent_context": result["targets"][cid]["parent_text"],
                "passage": next(p["text"] for p in result["pools"][cid] if p["passage_id"] == pid),
            },
            "blinded row payload/mapping mismatch or field leak",
        )
    if not calibration_passed or a != b or any(x[0] == "needs-review" for x in a.values()):
        return {
            "primary_disposition": "INCONCLUSIVE",
            "reason": "calibration/disagreement/uncertainty",
        }
    values = {tuple(mapping["mapping"][alias]): pair for alias, pair in a.items()}
    m = metrics(result, values)
    return {
        **decide(m),
        "metrics": m,
        "review_artifact_payload_sha256": [digest(canonical(r)) for r in reviews],
        "semantic_authority": "supplied frozen reviewer judgments",
    }


def compare_replays(first: Path, second: Path) -> None:
    """Verify every emitted research/native artifact, not just a selected JSON value."""
    a, b = load(first / "COMPLETED.PUBLIC.json"), load(second / "COMPLETED.PUBLIC.json")
    require(a["ordinal"] == 1 and b["ordinal"] == 2, "replay ordinal/budget mismatch")
    require(a["hashes"] == b["hashes"], "raw-byte replay hash mismatch")
    names = {
        "retrieval_output_raw_sha256": "RETRIEVAL.PRIVATE.json",
        "nomination_trace_raw_sha256": "NOMINATION-TRACE.PRIVATE.json",
    }
    require(
        set(names) <= set(a["hashes"]) and len(a["hashes"]) == 14,
        "two research artifacts and twelve native baselines required",
    )
    for key, expected in a["hashes"].items():
        filename = names.get(key, key)
        require(Path(filename).name == filename, "replay path escape")
        left, right = first / filename, second / filename
        require(not left.is_symlink() and not right.is_symlink(), "replay symlink substitution")
        require(
            digest(left.read_bytes()) == expected
            and digest(right.read_bytes()) == expected
            and left.read_bytes() == right.read_bytes(),
            "raw-byte replay drift",
        )
    expected_names = {names.get(key, key) for key in a["hashes"]} | {
        "STARTED.PUBLIC.json",
        "COMPLETED.PUBLIC.json",
    }
    require(
        {p.name for p in first.iterdir()} == expected_names
        and {p.name for p in second.iterdir()} == expected_names,
        "unexpected replay artifacts or incomplete attempt",
    )
    result = load(first / "RETRIEVAL.PRIVATE.json")
    trace = load(first / "NOMINATION-TRACE.PRIVATE.json")
    require(
        result["binding"]["nomination_trace_payload_sha256"] == digest(canonical(trace)),
        "nomination trace binding mismatch",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=["build-packet", "tally"])
    parser.add_argument("--result", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--salt")
    parser.add_argument("--replay-result", type=Path)
    parser.add_argument("--packet", type=Path)
    parser.add_argument("--mapping", type=Path)
    parser.add_argument("--review", type=Path, action="append")
    parser.add_argument("--control-packet", type=Path)
    parser.add_argument("--control-review", type=Path, action="append")
    args = parser.parse_args()
    exposed = False
    try:
        require(
            not args.out_dir.exists() and not args.out_dir.is_symlink(), "stale output location"
        )
        result = load(args.result)
        require(
            args.result.name == "RETRIEVAL.PRIVATE.json" and args.replay_result is not None,
            "both completed retrieval artifacts required",
        )
        compare_replays(args.result.parent, args.replay_result.parent)
        from bind import verify_chain

        require(
            args.result.parent.name == "retrieval-01"
            and args.replay_result.parent == args.result.parent.parent / "retrieval-02",
            "retrieval cohort binding",
        )
        verify_chain(args.result.parent.parent, 4)
        if args.command == "build-packet":
            require(
                isinstance(args.salt, str) and len(args.salt) >= 32,
                "private blinding salt required",
            )
            packet, mapping = build_packet(result, args.salt)
            fresh_directory(args.out_dir)
            write_new(args.out_dir / "REVIEW-PACKET.PRIVATE.json", packet)
            write_new(args.out_dir / "MAPPING.PRIVATE.json", mapping)
        else:
            require(
                all(
                    [
                        args.packet,
                        args.mapping,
                        args.review,
                        args.control_packet,
                        args.control_review,
                    ]
                ),
                "frozen live calibration evidence required",
            )
            control = load(args.control_packet)
            expected_control = load(HERE / "CONTROLS.json")["packet"]
            require(control == expected_control, "wrong evaluator control packet")
            control_reviews = [load(p) for p in args.control_review]
            exposed = True
            passed = calibrate(control, load(HERE / "CONTROLS.json")["gold"], control_reviews)
            if not passed:
                fresh_directory(args.out_dir)
                write_new(
                    args.out_dir / "RESULT.PUBLIC.json",
                    {
                        "primary_disposition": "INCONCLUSIVE",
                        "reason": "semantic evaluator controls failed",
                        "decisive_review_read": False,
                    },
                )
                return 0
            require(
                args.packet.read_bytes() == canonical(load(args.packet))
                and args.mapping.read_bytes() == canonical(load(args.mapping)),
                "noncanonical frozen packet/mapping raw-byte substitution",
            )
            review_values = [load(p) for p in args.review]
            require(
                len(review_values) == 2
                and all(r["model_id"] == control_reviews[0]["model_id"] for r in review_values),
                "qualified model/profile mismatch",
            )
            require(
                not {r["session_id"] for r in review_values}.intersection(
                    r["session_id"] for r in control_reviews
                ),
                "calibration history reused in decisive review",
            )
            output = tally(result, load(args.packet), load(args.mapping), review_values, passed)
            fresh_directory(args.out_dir)
            # IDs/per-row observations stay private; public receipt carries aggregates only.
            write_new(args.out_dir / "RESULT.PRIVATE.json", output)
            public = {
                key: output[key]
                for key in output
                if key not in {"metrics", "review_artifact_payload_sha256"}
            }
            if "metrics" in output:
                public["aggregate_counts"] = {
                    arm: {
                        k: v
                        for k, v in m.items()
                        if k not in {"per_child", "per_parent", "per_packet"}
                    }
                    for arm, m in output["metrics"].items()
                }
            public["raw_review_file_sha256"] = [digest(p.read_bytes()) for p in args.review]
            write_new(args.out_dir / "RESULT.PUBLIC.json", public)
        return 0
    except (BoundaryError, OSError, TypeError, KeyError) as exc:
        print(json.dumps({"state": "INCONCLUSIVE" if exposed else "BLOCKED", "error": str(exc)}))
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
